### ISSUE TITLE
Add fully designed features

### ISSUE THREAD

**Issue by mejackreed** [ProjectMirador/mirador-image-tools#3]
Ticket ported from https://github.com/ProjectMirador/mirador/issues/1985

![plugin menu adjust](https://user-images.githubusercontent.com/6945691/54859865-7cf6c880-4ccf-11e9-95b1-14a7303c5cd7.gif)

- add "Adjust image" option to the window menu, in the section below view/thumbnails
- on select, close the menu and open the "Adjust image" toolbar
- toolbar is horizontal above the mobile breakpoint; vertical below it
   - note that we may want a configuration option to set the default orientation for the toolbar - manuscripts with vertical text will prefer a vertical toolbar that doesn't cut off the first character of each column
- toolbar has its own close button
- icon tooltips appear below or to the left, depending on the orientation of the toolbar
- toolbar pattern is meant be used for other tools & plugins as well - annotations, ruler, etc. 

The illustrated set of icons represents what's implemented in Mirador2:
<img width="1462" alt="Screen Shot 2019-03-22 at 6 40 05 PM" src="https://user-images.githubusercontent.com/6945691/54860071-0c04e000-4cd2-11e9-8e5d-a437f7c80c48.png">

Partial implementation with Brightness/Contrast alone would look like so:
<img width="369" alt="Screen Shot 2019-03-22 at 6 28 45 PM" src="https://user-images.githubusercontent.com/6945691/54859951-67ce6980-4cd0-11e9-8496-3d52f9742c51.png">

✅ | Tooltip | Icon (MUI name)
--- | --- | ---
[x] | Adjust image (menu option) | tune
[x] | Brightness | brightness_5
[x] | Contrast | ExposureSharp rotated
[x] | Greyscale | tonality (different from mockups)
[x] | Invert colors | invert_colors
[x] | Rotate right | rotate_right
[ ] | Rotate left | rotate_left
[x] | Flip horizontal | compare_arrows
[ ] | Flip vertical | compare_arrows rotated
[ ] | Revert image | refresh
[x] | Expand/collapse toolbar | close

**Comment by cbeer** [comment]
Toggle invert / greyscale.

**Comment by mejackreed** [comment]
This has all been added.
